# Jackson Gawarecki
## Individual Project 5
### DS160-02 Introduction to Data Science
#### Spring 2022

In [28]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 

In [29]:
df=pd.read_csv("Self Awareness Dataset.csv")
df.head()

Date       Day  Sleep Hour  Exercise Hour  Study Hour  StudyDS Hour  \
0  13-Jan  Thursday         8.0            2.0         2.0          0.25   
1  14-Jan    Friday         9.0            2.0         2.0          0.00   
2  15-Jan  Saturday         8.0            2.0         1.0          0.00   
3  16-Jan    Sunday        11.0            2.0         0.0          0.00   
4  17-Jan    Monday         8.0            3.0         2.0          0.00   

   Work Hour  End of the day Feeling (0 to 10)  Unnamed: 8  Unnamed: 9  \
0        4.0                               7.0         NaN         NaN   
1        4.0                               8.0         NaN         NaN   
2        4.0                               6.0         NaN         NaN   
3        4.0                               8.0         NaN         NaN   
4        4.0                               8.0         NaN         NaN   

   Unnamed: 10                                        Unnamed: 11  
0          NaN                                                NaN  
1          NaN                                                NaN  
2          NaN                                                NaN  
3          NaN  Feeling: 0 (‘not at all’) to 10 (‘extremely’) ...  
4          NaN                                                NaN

# Check for Null values

In [30]:
df.isnull().sum()

Date                                 5
Day                                  5
Sleep Hour                           5
Exercise Hour                        5
Study Hour                           5
StudyDS Hour                         5
Work Hour                            5
End of the day Feeling (0 to 10)     5
Unnamed: 8                          73
Unnamed: 9                          73
Unnamed: 10                         73
Unnamed: 11                         71
dtype: int64

In [31]:
df.tail()

Date  Day  Sleep Hour  Exercise Hour  Study Hour  StudyDS Hour  Work Hour  \
68  NaN  NaN         NaN            NaN         NaN           NaN        NaN   
69  NaN  NaN         NaN            NaN         NaN           NaN        NaN   
70  NaN  NaN         NaN            NaN         NaN           NaN        NaN   
71  NaN  NaN         NaN            NaN         NaN           NaN        NaN   
72  NaN  NaN         NaN            NaN         NaN           NaN        NaN   

    End of the day Feeling (0 to 10)  Unnamed: 8  Unnamed: 9  Unnamed: 10  \
68                               NaN         NaN         NaN          NaN   
69                               NaN         NaN         NaN          NaN   
70                               NaN         NaN         NaN          NaN   
71                               NaN         NaN         NaN          NaN   
72                               NaN         NaN         NaN          NaN   

   Unnamed: 11  
68         NaN  
69         NaN  
70         NaN  
71         NaN  
72         NaN

# Remove the last five rows

In [32]:
df.drop(df.tail(5).index,
        inplace = True)

In [33]:
df.tail()

Date       Day  Sleep Hour  Exercise Hour  Study Hour  StudyDS Hour  \
63  17-Mar  Thursday         8.0            2.0         1.0           1.0   
64  18-Mar    Friday         7.0            1.0         1.0           0.0   
65  19-Mar  Saturday         8.0            2.0         0.0           0.0   
66  20-Mar    Sunday         8.0            2.0         0.0           0.0   
67  21-Mar    Monday         9.0            3.0         2.0           1.0   

    Work Hour  End of the day Feeling (0 to 10)  Unnamed: 8  Unnamed: 9  \
63        4.0                               9.0         NaN         NaN   
64        1.0                               8.0         NaN         NaN   
65        2.0                               8.0         NaN         NaN   
66        3.0                               9.0         NaN         NaN   
67        3.0                               7.0         NaN         NaN   

    Unnamed: 10 Unnamed: 11  
63          NaN         NaN  
64          NaN         NaN  
65          NaN         NaN  
66          NaN         NaN  
67          NaN         NaN

# Remove blank columns

In [34]:
df.columns

Index(['Date', 'Day', 'Sleep Hour', 'Exercise Hour', 'Study Hour',
       'StudyDS Hour', 'Work Hour', 'End of the day Feeling (0 to 10)',
       'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11'],
      dtype='object')

In [35]:
df.drop(['Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11'],
        axis=1, inplace=True)

# Split dataset into independent and dependent variables

In [36]:
df.columns

Index(['Date', 'Day', 'Sleep Hour', 'Exercise Hour', 'Study Hour',
       'StudyDS Hour', 'Work Hour', 'End of the day Feeling (0 to 10)'],
      dtype='object')

In [37]:
X=df[['Day', 'Sleep Hour', 'Exercise Hour', 'Study Hour',
       'StudyDS Hour', 'Work Hour']]
y=df[['End of the day Feeling (0 to 10)']]

In [38]:
X=pd.get_dummies(df[['Day', 'Sleep Hour', 'Exercise Hour', 'Study Hour',
       'StudyDS Hour', 'Work Hour']],drop_first=True)
X.head()

Sleep Hour  Exercise Hour  Study Hour  StudyDS Hour  Work Hour  Day_Monday  \
0         8.0            2.0         2.0          0.25        4.0           0   
1         9.0            2.0         2.0          0.00        4.0           0   
2         8.0            2.0         1.0          0.00        4.0           0   
3        11.0            2.0         0.0          0.00        4.0           0   
4         8.0            3.0         2.0          0.00        4.0           1   

   Day_Saturday  Day_Sunday  Day_Thursday  Day_Tuesday  Day_Wednesday  
0             0           0             1            0              0  
1             0           0             0            0              0  
2             1           0             0            0              0  
3             0           1             0            0              0  
4             0           0             0            0              0

In [39]:
y.head()

End of the day Feeling (0 to 10)
0                               7.0
1                               8.0
2                               6.0
3                               8.0
4                               8.0

# Splitting the data into Training and Test set

In [40]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [41]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.2, random_state=42)

# Training the Multiple Linear Regression model on the training set

In [42]:
regressor=LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression()

In [43]:
print('Coefficient', regressor.coef_)
print('Intercept', regressor.intercept_)

Coefficient [[-0.13668617 -0.05926067 -0.1798232   0.28669759  0.04683262 -0.53000841
  -0.53376948  0.14430952  0.0423296  -0.39567728 -0.16976282]]
Intercept [8.89331828]


# Predicting the Test set results

In [44]:
y_pred=regressor.predict(X_test)

# Validation

In [45]:
regressor.predict([[8,2,1,1,4,0,0,0,1,0,0]])

array([[8.01784204]])

In [46]:
regressor.predict([[7,1,1,0,1,0,0,0,0,0,0]])

array([[7.74426383]])

In [47]:
regressor.predict([[8,2,0,0,2,0,1,0,0,0,0]])

array([[7.24120334]])

In [48]:
regressor.predict([[8,2,0,0,3,0,0,1,0,0,0]])

array([[7.96611496]])

In [49]:
regressor.predict([[9,3,2,1,3,1,0,0,0,0,0]])

array([[7.02290136]])

# R2 Score, Coefficients, Intercepts

In [50]:
from sklearn.metrics import r2_score
print('R-Square',r2_score(y_test,y_pred))

R-Square -0.5390920251690099


In [51]:
print('Coefficient', regressor.coef_)
print('Intercept', regressor.intercept_)

Coefficient [[-0.13668617 -0.05926067 -0.1798232   0.28669759  0.04683262 -0.53000841
  -0.53376948  0.14430952  0.0423296  -0.39567728 -0.16976282]]
Intercept [8.89331828]


In [52]:
model=sm.OLS(y,X).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                        OLS Regression Results                                       
=====================================================================================================
Dep. Variable:     End of the day Feeling (0 to 10)   R-squared (uncentered):                   0.985
Model:                                          OLS   Adj. R-squared (uncentered):              0.983
Method:                               Least Squares   F-statistic:                              349.0
Date:                              Mon, 21 Mar 2022   Prob (F-statistic):                    4.90e-48
Time:                                      21:35:11   Log-Likelihood:                         -91.693
No. Observations:                                68   AIC:                                      205.4
Df Residuals:                                    57   BIC:                                      229.8
Df Model:                                        11                                                  
Covariance Type:                          nonrobust                                                  
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
Sleep Hour        0.6389      0.084      7.592      0.000       0.470       0.807
Exercise Hour    -0.0991      0.206     -0.481      0.632      -0.511       0.313
Study Hour       -0.0037      0.197     -0.019      0.985      -0.399       0.391
StudyDS Hour     -0.1003      0.324     -0.310      0.758      -0.749       0.548
Work Hour         0.7461      0.237      3.154      0.003       0.272       1.220
Day_Monday       -0.0054      0.478     -0.011      0.991      -0.962       0.951
Day_Saturday     -0.0243      0.466     -0.052      0.959      -0.957       0.908
Day_Sunday       -0.6524      0.678     -0.963      0.340      -2.009       0.705
Day_Thursday      0.3746      0.489      0.766      0.447      -0.604       1.353
Day_Tuesday       0.6966      0.517      1.347      0.183      -0.339       1.732
Day_Wednesday     0.5629      0.488      1.153      0.254      -0.415       1.540
==============================================================================
Omnibus:                        6.356   Durbin-Watson:                   1.176
Prob(Omnibus):                  0.042   Jarque-Bera (JB):                5.589
Skew:                           0.668   Prob(JB):                       0.0612
Kurtosis:                       3.432   Cond. No.                         69.5
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [53]:
X.columns

Index(['Sleep Hour', 'Exercise Hour', 'Study Hour', 'StudyDS Hour',
       'Work Hour', 'Day_Monday', 'Day_Saturday', 'Day_Sunday', 'Day_Thursday',
       'Day_Tuesday', 'Day_Wednesday'],
      dtype='object')

In [56]:
X1=X[['Sleep Hour', 'Work Hour']]

In [57]:
sm.OLS(y,X1).fit().summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                        OLS Regression Results                                       
=====================================================================================================
Dep. Variable:     End of the day Feeling (0 to 10)   R-squared (uncentered):                   0.982
Model:                                          OLS   Adj. R-squared (uncentered):              0.981
Method:                               Least Squares   F-statistic:                              1773.
Date:                              Mon, 21 Mar 2022   Prob (F-statistic):                    4.39e-58
Time:                                      21:39:18   Log-Likelihood:                         -99.253
No. Observations:                                68   AIC:                                      202.5
Df Residuals:                                    66   BIC:                                      206.9
Df Model:                                         2                                                  
Covariance Type:                          nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Sleep Hour     0.7201      0.067     10.712      0.000       0.586       0.854
Work Hour      0.5469      0.117      4.660      0.000       0.313       0.781
==============================================================================
Omnibus:                        0.277   Durbin-Watson:                   1.197
Prob(Omnibus):                  0.870   Jarque-Bera (JB):                0.462
Skew:                           0.076   Prob(JB):                        0.794
Kurtosis:                       2.626   Cond. No.                         8.93
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

# *Sleep and Work Hours are the only Significant factors of Happiness for the Day*